name: Theme Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'unax.zip'
        exclusions: '*.git* *.github* /*node_modules/* /vendor .gitignore .distignore composer.* gulp* package.json phpcs.xml.dist README.md'
